server:
  port: 8010
spring: 
  application:
    name: docker-learn

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true    
    